# Generated by Django 6.0.3 on 2026-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo_cin',
            field=models.ImageField(blank=True, null=True, upload_to='clients/cin/', verbose_name='Photo CIN'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='document_joint',
            field=models.FileField(blank=True, null=True, upload_to='interventions/documents/'),
        ),
    ]
