# Generated by Django 6.0.3 on 2026-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_audience_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='avocat',
        ),
        migrations.AddField(
            model_name='dossier',
            name='partie_adverse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Partie Adverse (Khesm)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='tribunal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tribunal Compétent'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='type_affaire',
            field=models.CharField(choices=[('Civil', 'Droit Civil'), ('Penal', 'Droit Pénal'), ('Commercial', 'Droit Commercial'), ('Famille', 'Droit de la Famille'), ('Travail', 'Droit du Travail'), ('Administratif', 'Droit Administratif'), ('Autre', 'Autre')], default='Civil', max_length=50),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé des Faits'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Clôturé', 'Clôturé'), ('Archivé', 'Archivé')], default='En cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
