# Generated by Django 6.0.3 on 2026-05-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_remove_dossier_avocat_dossier_partie_adverse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='dossiers/documents/'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='partie_adverse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Partie Adverse '),
        ),
    ]
