# Generated by Django 6.0.3 on 2026-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_alter_document_fichier_alter_dossier_partie_adverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Prénom'),
            preserve_default=False,
        ),
    ]
